language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get update
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;     
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes -q conda
install:
  - conda install --yes -q python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -q -c conda-forge `cat requirements.txt`
  - pip install travis-sphinx codacy-coverage python-coveralls codecov
  - python setup.py install
script:
  - nosetests --with-coverage
  - coverage xml
after_success:
  - codecov
  - coveralls
  - python-codacy-coverage -r coverage.xml
