language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;     
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION
  - conda install --yes `cat requirements.txt`
  - conda install --yes -c conda-forge nodejs python-coveralls nbsphinx sphinx_rtd_theme
  - pip install travis-sphinx codacy-coverage codecov
  - python setup.py install
script:
  - nosetests --with-coverage
  - coverage xml
  - travis-sphinx -n build
after_success:
  - codecov
  - coveralls
  - python-codacy-coverage -r coverage.xml
  - travis-sphinx -n deploy
